# Generated by Django 5.0.3 on 2024-04-01 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Grupo', models.CharField(max_length=50, unique=True)),
                ('Info', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('url_imagen', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('tocken2FA', models.BooleanField()),
                ('strToken', models.CharField(blank=True, max_length=50, null=True)),
                ('online', models.BooleanField()),
                ('Foto_Perfil', models.ImageField(null=True, upload_to='')),
                ('url_foto_perfil', models.CharField(max_length=500, null=True)),
                ('Nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('Apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('Pais', models.CharField(blank=True, max_length=50, null=True)),
                ('Ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('Info', models.CharField(blank=True, max_length=500, null=True)),
                ('Fecha_Nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contacto_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.BooleanField()),
                ('Grupo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.grupo')),
                ('Usuario_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion_Grupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('url_imagen', models.CharField(max_length=500, null=True)),
                ('token', models.CharField(editable=False, max_length=500, unique=True)),
                ('Grupo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.grupo')),
                ('Grupo_Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.grupo_member')),
            ],
        ),
        migrations.CreateModel(
            name='Like_Publicacion_Grupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrupoMember_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.grupo_member')),
                ('Publicacion_Grupal_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.publicacion_grupal')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario_Publicacion_Grupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TextField(blank=True, null=True)),
                ('Grupo_Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.grupo_member')),
                ('Publicacion_Grupal_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.publicacion_grupal')),
            ],
        ),
        migrations.CreateModel(
            name='ResetPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strToken', models.CharField(blank=True, max_length=50, null=True)),
                ('cant_intentos', models.IntegerField()),
                ('UsuarioID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion_Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=500, unique=True)),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('url_imagen', models.CharField(max_length=500, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('UsuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Like_Publicacion_Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publicacion_Personal_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.publicacion_personal')),
                ('Usuario_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.TextField()),
                ('Fecha', models.DateTimeField()),
                ('Grupo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.grupo')),
                ('Usuario_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.TextField()),
                ('Fecha', models.DateTimeField()),
                ('Chat_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.chat')),
                ('Usuario_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='ContactoUser_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='App.usuario'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='Usuario_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duenio', to='App.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario_Publicacion_Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TextField(blank=True, null=True)),
                ('Publicacion_Personal_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.publicacion_personal')),
                ('Usuario_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grupo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.grupo')),
                ('Usuario_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
            options={
                'unique_together': {('Grupo_ID', 'Usuario_ID')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='contacto',
            unique_together={('Usuario_ID', 'ContactoUser_ID')},
        ),
    ]
