# Generated by Django 5.0.3 on 2024-04-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion_grupal',
            name='token',
            field=models.CharField(editable=False, max_length=250, unique=True),
        ),
    ]
