# Generated by Django 5.0.3 on 2024-04-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_publicacion_grupal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='Info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='url_imagen',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion_grupal',
            name='url_imagen',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion_personal',
            name='token',
            field=models.CharField(editable=False, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='publicacion_personal',
            name='url_imagen',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='url_foto_perfil',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
